### ISSUE TITLE
Feature Request: Add option to make ImageKitModule global

### ISSUE THREAD

**Issue by RATCHAW** [CodeVisionEvgen/imagekit-nestjs#1]
Hi there,

I have a feature request that I believe would improve the usability of this module
Currently, to use the ImageKitModule, we need to import it into every module where we want to use the ImageKitService. This can lead to repetitive code and make it harder to manage the module's usage across a large application.

Feature Request:
It would be extremely helpful if there was an option to make the ImageKitModule global. This could be implemented in a way similar to how other NestJS modules handle global configuration. For example:

```typescript
ImageKitModule.forRootAsync({
  isGlobal: true,
  useFactory: async (configService) => imageKitConfig(configService),
  inject: [ConfigService],
})

**Comment by CodeVisionEvgen** [comment]
Ok, I'll add it soon, thanks for using the module

пт, 2 серп. 2024, 21:58 користувач AYOUB BENDARSI ***@***.***>
пише:

**Comment by CodeVisionEvgen** [comment]
Close
